### PR TITLE
#75 #76 fixed flex issue and added onKeyDown function

### LINKED ISSUE #75: Fix flexbox issues in ToggleSwitch

### PR DESCRIPTION
**Pull request by josephhofmeister-orbis**
fixed #75 and #76. 

I also fixed an issue I saw in firefox where the color of dropdowns wasn't white (they're white be default in chrome, gray in firefox).

### CODE REVIEW

File: lib/components/FormInput.jsx [hunk 1]
```diff
@@ -87,21 +90,51 @@ const FormInput = ({ formInputID = "", ...props }) => {
...
+        <textarea
+          id={formInputID}
+          name={formInputID}
+          placeholder={placeholderText}
+          rows={textareaRows}
+          // cols={textareaColumns} 
+          value={inputValue}
+          disabled={inputDisabled}
+          onChange={(event) => { handleOnChange(event); }}
+          onKeyDown={(event) => { onKeyDown(event); }}
```
Comment (joshwaller-oe) [inline lib/components/FormInput.jsx:102]: this can be shortened because `event` is always the default return argument, ie:
`onKeyDown={onKeyDown}`

this is also the same situation with `onChange` above:
`onChange={handleOnChange}`

File: lib/components/FormInput.jsx [hunk 2]
```diff
@@ -87,21 +90,51 @@ const FormInput = ({ formInputID = "", ...props }) => {
...
       {inputType !== "textarea" && inputType !== "toggle" && inputType !== "password" && inputType !== "color" ?
 
-        <input type={inputType} id={formInputID} placeholder={placeholderText} value={inputValue} disabled={inputDisabled} onChange={(event) => handleOnChange(event)} min={inputMin} max={inputMax} step={inputStep} list={datalistName} autoFocus={autoFocus} />
+        <input
+          type={inputType}
+          id={formInputID}
+          placeholder={placeholderText}
+          value={inputValue}
+          disabled={inputDisabled}
+          onChange={(event) => { handleOnChange(event); }}
```
Comment (joshwaller-oe) [inline lib/components/FormInput.jsx:116]: same thing in terms of shortened usage:
`onChange={handleOnChange}`

**Review by joshwaller-oe — CHANGES_REQUESTED** [review]
@josephhofmeister-orbis I had some feedback on shortening the functions being passed to the element event properties. The event is the default argument returned in 1st position so you can shorten things like this: `onChange={(event) => handleOnChange(event)}` to this `onChange={handleOnChange}`

Other thing to mention is you'll need to increment the version within the `package.json` and run an `npm i` to update the `package-lock.json`

**Comment by joshwaller-oe** [comment]
> @joshwaller-oe While I do understand why it can be shortened, I just like to default to being more verbose. I feel like it's more clear what is going to happen here, and if anything else needs to be added in the future, either another parameter, function, a quick console.log, etc., I like that the line is already set up for me to easily do so. I don't mind changing if you disagree though.
> 
> Also, the package-lock.json should be updated now!

@josephhofmeister-orbis That makes sense. I'm used to adding _if_ needed approach, but I get your direction as well. I'm fine if you want to keep. ✅

**Review by joshwaller-oe — APPROVED** [review]

**Review by mrfisher-oe — APPROVED** [review]
